# Generated by Django 4.2.7 on 2025-06-15 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherassignment",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="academics.academicsession",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_classes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="academicsession",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_sessions",
                to="schools.school",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="term",
            unique_together={("academic_session", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="teacherassignment",
            unique_together={
                ("teacher", "class_assigned", "subject", "academic_session")
            },
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("school", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("school", "name", "academic_session")},
        ),
        migrations.AlterUniqueTogether(
            name="academicsession",
            unique_together={("school", "name")},
        ),
    ]
